### ISSUE TITLE
Pre-trained models are missing

### ISSUE THREAD

**Issue by mrerdem** [Neural-Dreamers/ESC-NAS#1]
Pre-trained are missing despite the readme: "There are pretrained models resulting for each dataset from ESC-NAS are provided inside torch/resources/trained_models directory that can be used instead of training a new model."

Is it possible to add them?

**Comment by thivindu** [comment]
Thank you for pointing out the mistake.
I have resolved the issue by adding the pre-trained models for FSC22, ESC-10, ESC-50 and Urbansound8K datasets.
Thank you.
